name: CI/CD

# on:
#   pull_request:
#     branches: [ master ]
  
# Exclude the workflow to run on changes to the helm chart
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go 1.22
      uses: actions/setup-go@v2
      with:
        go-version: 1.22
      id: go

    - name: Build
      run: go build -o go-web-app
    - name: Test
      run: go test -cover ./...

  # check:
  #   name: check
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Set up GOPATH
  #     - name: set up
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.22'
  #       id: go
  #     # Check out this repository
  #     - name: checkout
  #       uses: actions/checkout@v4
      # Store cache
      # - name: cache
      #   uses: actions/cache@v4.0.2
      #   with:
      #     path: ~/go/pkg/mod
      #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-go-
      # # Run golangci-lint using reviewdog
      # - name: golangci-lint
      #   uses: reviewdog/action-golangci-lint@v2
      #   with:
      #     github_token: ${{ secrets.github_token }}
      #     level: warning
      #     golangci_lint_flags: "--config=.github/.golangci.yml"
      #     reporter: github-pr-review
      # # Run test
      # - name: test
      #   run: go test -cover ./...

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.56.2
  
  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/webapp:${{github.run_id}}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/webapp/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "mahinraza556@gmail.com"
        git config --global user.name "Mahin raza"
        git add helm/webapp/values.yaml
        git commit -m "Update tag in Helm chart"
        git push